---
title: "Final URSSI Figures"
author: "Jessica Young and Karthik Ram"
output:
  html_document:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

pacman::p_load(
    dplyr,
    viridis,
    viridisLite,
    ggplot2,
    stringr,
    reshape2,
    flextable,
    DT,
    VIM,
    gplots,
    RColorBrewer,
    corrplot,
    knitr,
    gridExtra,
    grid,
    gridGraphics,
    # SparseDC,
    broom,
    irr,
    listviewer,
    formattable,
    sp,
    maps,
    maptools,
    revgeo,
    mapproj,
    emmeans
)

dat <- read.csv("urssi_survey_data_2019_12_24.csv", stringsAsFactors = F)[-c(1:2), -c(1:3, 6, 8:13, 16:17)]

rownames(dat) <- read.csv("urssi_survey_data_2019_12_24.csv", stringsAsFactors = F)[-c(1:2), 9]

info_cols <- as.character(read.csv("urssi_survey_data_2019_12_24.csv", stringsAsFactors = F)[1, -c(1:3, 6, 8:13, 16:17)])

dat$Progress <- as.numeric(as.character(dat$Progress))

dat_na = as.data.frame(apply(dat, 2, function(x)
    ifelse(x == "", NA, x)), stringsAsFactors = F)

source("functions.R")
```


```{r figure1}
knitr::opts_chunk$set(fig.width = 14, fig.height = 14)
dat1 = dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1,
           Q3.3_1,
           Q3.3_2,
           Q3.3_3,
           Q3.3_4,
           Q3.3_5,
           Q3.3_6,
           Q3.3_7,
           Q3.3_8,
           Q3.3_9,
           Q3.3_10)

dat2 = dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1,
           Q3.4_1,
           Q3.4_2,
           Q3.4_3,
           Q3.4_4,
           Q3.4_5,
           Q3.4_6,
           Q3.4_7,
           Q3.4_8,
           Q3.4_9,
           Q3.4_10)

datm1 = reshape2::melt(dat1, id.vars = 'Q1.1') %>%
    mutate(Time = 'SpentTime')
datm2 = reshape2::melt(dat2, id.vars = 'Q1.1') %>%
    mutate(Time = 'IdealSpentTime')

datm1 =  datm1 %>%
    mutate(
        value = as.numeric(value),
        Question = as.character(variable),
        Question = ifelse(
            Question == "Q3.3_1",
            "Requirements",
            ifelse(
                Question == "Q3.3_2",
                "Software",
                ifelse(
                    Question == "Q3.3_3",
                    "Coding",
                    ifelse(
                        Question == "Q3.3_4",
                        "Testing",
                        ifelse(
                            Question == "Q3.3_5",
                            "Debugging",
                            ifelse(
                                Question == "Q3.3_6",
                                "Maintenance",
                                ifelse(
                                    Question == "Q3.3_7",
                                    "Documentation",
                                    ifelse(
                                        Question == "Q3.3_8",
                                        "Meetings",
                                        ifelse(
                                            Question == "Q3.3_9",
                                            "Training",
                                            ifelse(Question == "Q3.3_10", "Other", NA)
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    ) %>%
    select(-variable)

datm2 =  datm2 %>%
    mutate(
        value = as.numeric(value),
        Question = as.character(variable),
        Question = ifelse(
            Question == "Q3.4_1",
            "Requirements",
            ifelse(
                Question == "Q3.4_2",
                "Software",
                ifelse(
                    Question == "Q3.4_3",
                    "Coding",
                    ifelse(
                        Question == "Q3.4_4",
                        "Testing",
                        ifelse(
                            Question == "Q3.4_5",
                            "Debugging",
                            ifelse(
                                Question == "Q3.4_6",
                                "Maintenance",
                                ifelse(
                                    Question == "Q3.4_7",
                                    "Documentation",
                                    ifelse(
                                        Question == "Q3.4_8",
                                        "Meetings",
                                        ifelse(
                                            Question == "Q3.4_9",
                                            "Training",
                                            ifelse(Question == "Q3.4_10", "Other", NA)
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    ) %>%
    select(-variable)

datm = rbind(datm1, datm2) %>%
    mutate(Question = factor(
        Question,
        levels = c(
            "Requirements",
            "Software",
            "Coding",
            "Testing",
            "Debugging",
            "Maintenance",
            "Documentation",
            "Meetings",
            "Training",
            "Other"
        )
    ))


datm$Question <- recode_factor(datm$Question, Software = "Design")
foo <- levels(datm$Question)
datm$Question <-
    forcats::fct_relevel(datm$Question, "Requirements", "Design")

library(viridis)
figure1 <- datm %>%
    ggplot(aes(x = Q1.1, fill = Time, y = value)) +
    facet_wrap(vars(Question)) +
    scale_fill_viridis(discrete = TRUE) +
    geom_boxplot(fatten = NULL, outlier.size = .5) +
    stat_summary(
        fun = mean,
        geom = "errorbar",
        aes(ymax = ..y.., ymin = ..y..),
        width = .75,
        linetype = "solid",
        position = "dodge"
    ) +
    theme(
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
       plot.title = element_text(hjust = 0.5),
        legend.position = "bottom",
        axis.title.y = element_text(size = 12)
    ) +
    labs(
        y = "Percent of time"
    )   + theme(axis.text.x = element_text(vjust = -4),
                legend.spacing.x = unit(1.0, 'cm')) 
figure1
ggsave(
    file = "svg/figure_1.svg",
    plot = figure1,
    width = 16,
    height = 9
)
ggsave(
    file = "png/figure_1.png",
    plot = figure1,
    width = 16,
    height = 9
)

```


```{r figure2}
# FIGURE 2
dat <- dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1, Q11.2)

dat$`Project\nManagement` = ifelse(str_detect(dat$Q11.2, 'Project management') ==
                                       T, 'Yes', 'No')
dat$`Requirements\nelicitation/engineering` = ifelse(str_detect(dat$Q11.2, 'Requirements elicitation / engineering') ==
                                                         T,
                                                     'Yes',
                                                     'No')
dat$`Finding personnel/\nDeveloper turnover` = ifelse(str_detect(dat$Q11.2, 'Finding personnel / Developer turnover') ==
                                                          T,
                                                      'Yes',
                                                      'No')
dat$Communication = ifelse(
    str_detect(
        dat$Q11.2,
        'Communication (among those with different expertise, among different teams)'
    ) == T,
    'Yes',
    'No'
)
dat$`Use of best practices vs.\nneed for rapid delivery` = ifelse(
    str_detect(dat$Q11.2, 'Use of best practices vs. need for rapid delivery') ==
        T,
    'Yes',
    'No'
)
dat$`Keeping up with\nmodern tools` = ifelse(str_detect(dat$Q11.2, 'Keeping up with modern tools') ==
                                                 T,
                                             'Yes',
                                             'No')
dat$Porting = ifelse(str_detect(dat$Q11.2, 'Porting') == T, 'Yes', 'No')
dat$Testing = ifelse(str_detect(dat$Q11.2, 'Testing') == T, 'Yes', 'No')
dat$Debugging = ifelse(str_detect(dat$Q11.2, 'Debugging') == T, 'Yes', 'No')
dat$Other = ifelse(str_detect(dat$Q11.2, 'Other') == T, 'Yes', 'No')
dat$None = ifelse(str_detect(dat$Q11.2, 'None of the above') == T, 'Yes', 'No')

datm = reshape2::melt(dat[, -2], id.vars = 'Q1.1')
colnames(datm) = c('Q1.1', 'Aspects', 'Difficult')


datmm = datm %>%
    filter(Difficult == 'Yes')


figure2 <- ggplot(datmm, aes(x = Aspects, fill = Q1.1)) +
    geom_bar(color = "black", position = position_dodge2(width = 0.9, preserve = "single")) +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
    theme(
        axis.text.x = element_text(
            angle = 30,
            hjust = 1,
            size = rel(1.3)
            ),
        axis.text.y = element_text(
            hjust = 1,
            size = rel(1.3)
        ),
        legend.position = 'bottom',
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank() 
    )  +  scale_x_discrete(labels = c('Proj Mgt','Requirements','Personnel','Communication', 'Best Practices', 'Modern Tools', 'Porting', 'Testing', 'Debugging', 'Other', 'None'))

figure2
ggsave(
    file = "svg/figure_2.svg",
    plot = figure2,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_2.png",
    plot = figure2,
    width = 10,
    height = 8
)

tmp3 = dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    group_by(Q1.1) %>%
    tally()
```

```{r}
datm = reshape2::melt(dat_na[,-2], id.vars = 'Q1.1')
colnames(datm) = c('Q1.1', 'Areas', 'Willing')

tmp2 = datm %>%
  group_by(Q1.1, Areas) %>%
  filter(!is.na(Willing)) %>%
  tally()
```


```{r figure3, cache = TRUE}
# This is FIGURE 3
dat = dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1, Q3.5_1, Q3.5_2, Q3.5_3, Q3.5_4, Q3.5_5)

datm = reshape2::melt(dat, id.vars = 'Q1.1')
colnames(datm) = c('Q1.1', 'Question', 'Choice')

datm$Choice = factor(datm$Choice,
                     levels = c('Never', 'Rarely', 'Somewhat', "Frequently"))

datmm = datm %>%
    filter(!is.na(Choice))

figure3 <- ggplot(datmm, aes(x = Question, fill = Choice)) +
    facet_wrap('Q1.1') +
    scale_fill_viridis(discrete = TRUE) +
    geom_bar(position = "dodge", color = "black") +
    labs(x = '', y = 'Frequency') +
    scale_x_discrete(
        labels = c("Unit", "Integration", "System", "User", "Regression"),
        breaks = c("Q3.5_1", "Q3.5_2", "Q3.5_3", "Q3.5_4", "Q3.5_5")
    ) +
    theme(
        axis.text.x = element_text(angle = 35, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
          legend.title = element_blank()) 
figure3
ggsave(
    file = "svg/figure_3.svg",
    plot = figure3,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_3.png",
    plot = figure3,
    width = 10,
    height = 8
)

```



```{r figure4, cache = TRUE}

dat = dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1, Q4.3_1, Q4.3_2, Q4.3_3, Q4.3_4, Q4.3_5, Q4.3_6, Q4.3_7)

datm = reshape2::melt(dat, id.vars = 'Q1.1')
colnames(datm) = c('Profile', 'Question', 'Choice')

datm$Choice = factor(
    datm$Choice,
    levels = c(
        'Not supported at all',
        'Slightly supported',
        'Moderately supported',
        'Very supported',
        'Extremely supported'
    )
)
datm$Question = factor(datm$Question)
levels(datm$Question) = c(
    "Req. Gathering\n & Documentation",
    "Software Architecture\n& Design",
    "Coding",
    "Testing",
    "Debugging",
    "Maintenance",
    "Documentation"
)

datmm = datm %>%
    filter(!is.na(Choice))

figure4 <- ggplot(datmm, aes(x = Question, fill = Choice)) +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(
        axis.text.x = element_text(angle = 35, hjust = 1, size = rel(1.2)),
        legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank()
    ) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE))   +  scale_x_discrete(labels = c('Requirements','SW Architecture/Design','Coding', 'Testing', 'Debugging', 'Maintenance', 'Documentation'))
figure4
ggsave(
    file = "svg/figure_4.svg",
    plot = figure4,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_4.png",
    plot = figure4,
    width = 10,
    height = 8
)


```



```{r figure5}
dat = dat_na %>%
    filter(!is.na(Q1.1) & !is.na(Q5.4)) %>%
    select(Q1.1, Q5.4)

dat$Q5.4 = factor(dat$Q5.4)

figure5 <- ggplot(dat, aes(x = Q1.1, fill = Q5.4)) +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
          legend.title = element_blank()) 
figure5
ggsave(
    file = "svg/figure_5.svg",
    plot = figure5,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_5.png",
    plot = figure5,
    width = 10,
    height = 8
)

```



```{r figure6}
# This is FIGURE 6
dat <- dat_na %>%
    filter(!is.na(Q1.1) & !is.na(Q5.5)) %>%
    select(Q1.1, Q5.5)

dat$Q5.5 = factor(dat$Q5.5)

figure6 <- ggplot(dat, aes(x = Q1.1, fill = Q5.5)) +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
          legend.title = element_blank()) 
figure6
ggsave(
    file = "svg/figure_6.svg",
    plot = figure6,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_6.png",
    plot = figure6,
    width = 10,
    height = 8
)

```



```{r figure7}
dat = dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1,
           Q6.4_1,
           Q6.4_2,
           Q6.4_3,
           Q6.4_4,
           Q6.4_5,
           Q6.4_6,
           Q6.4_7,
           Q6.4_8,
           Q6.4_9)

datm = reshape2::melt(
    dat,
    id.vars = 'Q1.1',
    value.name = 'Choice',
    variable.name = 'Source'
)

datm$Choice = as.numeric(datm$Choice)


figure7 <- ggplot(datm, aes(x = Source, fill = Q1.1, y = Choice)) +
    geom_boxplot(fatten = NULL, outlier.size = .5) +
    scale_fill_viridis(discrete = TRUE) +
    stat_summary(
        fun = mean,
        geom = "errorbar",
        aes(ymax = ..y.., ymin = ..y..),
        width = .75,
        linetype = "solid",
        position = "dodge",
        color = "black"
    ) +
    labs(
        title = NULL,
        x = NULL,
        y = '% Funding',
        caption = "Middle line indicates mean."
    ) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
          legend.title = element_blank()) +
    scale_x_discrete(
        labels = c(
            "NSF",
            "NIH",
            "DoD",
            "DoE",
            "NASA",
            "NOAA",
            "Private Foundation",
            "Your own institution",
            "Other"
        ),
        breaks = c(
            "Q6.4_1",
            "Q6.4_2",
            "Q6.4_3",
            "Q6.4_4",
            "Q6.4_5",
            "Q6.4_6",
            "Q6.4_7",
            "Q6.4_8",
            "Q6.4_9"
        )
    ) 
figure7
ggsave(
    file = "svg/figure_7.svg",
    plot = figure7,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_7.png",
    plot = figure7,
    width = 10,
    height = 8
)

```




```{r figure8}
# This is FIGURE 8
dat <-   dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1, Q6.5_1, Q6.5_2, Q6.5_3, Q6.5_4)

datm = reshape2::melt(dat, id.vars = 'Q1.1')
colnames(datm) = c('Q1.1', 'Question', 'Choice')

datm$Question = ifelse(
    datm$Question == 'Q6.5_1',
    'Financial',
    ifelse(
        datm$Question == 'Q6.5_2',
        'Infrastructural',
        ifelse(
            datm$Question == 'Q6.5_3',
            'Consulting/ \n RSE Support',
            ifelse(datm$Question == 'Q6.5_4', 'Other', datm$Question)
        )
    )
)


datm$Choice = factor(
    datm$Choice,
    levels = c(
        'No',
        'Yes, but inadequate level of support',
        'Yes, adequate level of support'
    )
)

datmm = datm %>%
    filter(!is.na(Choice))




figure8 <- ggplot(datmm, aes(x = Question, fill = Choice)) +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(
        axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(),
        legend.position = 'bottom'
    ) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE)) 
figure8
ggsave(
    file = "svg/figure_8.svg",
    plot = figure8,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_8.png",
    plot = figure8,
    width = 10,
    height = 8
)

```



```{r figure10, cache = TRUE}
# This is figure 10
figure10 <-
    urssi_analysis2(dat_na, x = "Q1.1", fill = "Q7.3")  + scale_fill_viridis(discrete = TRUE) + 
    ggtitle("Opportunities For Career Advancement for Software Developers")
figure10
ggsave(
    file = "svg/figure_10.svg",
    plot = figure10,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_10.png",
    plot = figure10,
    width = 10,
    height = 8
)

```



```{r figure11}
dat <- dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Researchers') %>%
    select(Q1.1, Q7.4_1, Q7.4_2, Q7.4_3, Q7.4_4, Q7.4_5, Q7.4_6)

datm <- reshape2::melt(
    dat,
    id.vars = 'Q1.1',
    value.name = 'Choice',
    variable.name = 'Question'
)

datm$Choice <- factor(
    datm$Choice,
    levels = c(
        'Not at all important',
        'Slightly important',
        'Moderately important',
        'Very important',
        'Extremely important'
    )
)
datm$Question <- factor(datm$Question)
levels(datm$Question) = c(
    "Future staff",
    "Underrepresented groups",
    "Across disciplines",
    "Competing with industry",
    "Viable career path",
    "Outsource"
)

datmm <- datm %>% filter(!is.na(Choice))


figure11 <- ggplot(datmm, aes(x = Q1.1, fill = Choice)) +
    facet_wrap("Question") +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(
        axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(),
        legend.position = 'bottom'
    ) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE))  
figure11
ggsave(
    file = "svg/figure_11.svg",
    plot = figure11,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_11.png",
    plot = figure11,
    width = 10,
    height = 8
)

```


```{r figure12}
dat <- dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1, Q7.5_1, Q7.5_2, Q7.5_3, Q7.5_4, Q7.5_5, Q7.5_6)

datm = reshape2::melt(
    dat,
    id.vars = 'Q1.1',
    value.name = 'Choice',
    variable.name = 'Question'
)

datm$Choice = factor(
    datm$Choice,
    levels = c(
        'Not at all important',
        'Slightly important',
        'Moderately important',
        'Very important',
        'Extremely important'
    )
)
datm$Question = factor(datm$Question)
levels(datm$Question) = c(
    "Diversity",
    "Experience",
    "Background",
    "Diverse languages",
    "Across disciplines",
    "Growth"
)


datmm = datm %>%
    filter(!is.na(Choice))


figure12 <- ggplot(datmm, aes(x = Q1.1, fill = Choice)) +
    facet_wrap("Question") +
    geom_bar(position = "dodge", color = "black") +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
    theme(
        axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(),
        legend.position = 'bottom'
    ) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE)) + 
    ggtitle("Concerns When Being Hired As Software Development Staff")
figure12
ggsave(
    file = "svg/figure_12.svg",
    plot = figure12,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_12.png",
    plot = figure12,
    width = 10,
    height = 8
)

```


```{r figure14}
dat <- dat_na %>%
    filter(!is.na(Q1.1)) %>%
    select(Q1.1, Q8.2_1, Q8.2_2, Q8.2_3, Q8.2_4, Q8.2_5, Q8.2_6, Q8.2_7)

datm = reshape2::melt(
    dat,
    id.vars = 'Q1.1',
    value.name = 'Choice',
    variable.name = 'Question'
)

datm$Choice = factor(
    datm$Choice,
    levels = c(
        'Never',
        'Sometimes',
        'About half the timet',
        'Most of the time',
        'Always'
    )
)
datm$Question = factor(
    datm$Question,
    labels = c(
        "Q8.2_1" = "Cite paper about the software",
        "Q8.2_2" = "Cite the software user's manual",
        "Q8.2_3" = "Mention the name of the software",
        "Q8.2_4" = "Mention the URL of the software",
        "Q8.2_5" = "Cite the URL of the software",
        "Q8.2_6" = "Cite the published/archived software itself",
        "Q8.2_7" = "Other"
    )
)

datmm <- datm %>% filter(!is.na(Choice))
datmm$Choice <- droplevels(datmm$Choice)

figure14 <-
    datmm %>% filter(Question != "Other")  %>% ggplot(aes(x = Q1.1, fill = Choice)) +
    facet_wrap("Question", labeller = label_wrap_gen(width = 25)) +
    geom_bar(position = "dodge", color = "black") +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
    theme(
        axis.text.x = element_text(
            angle = 40,
            hjust = .9,
            size = rel(.8)
        ),
        plot.title = element_text(hjust = 0.5, size = rel(1.2)),
        legend.title = element_blank(),
        legend.position = 'bottom'
    ) 

figure14
ggsave(
    file = "svg/figure_14.svg",
    plot = figure14,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_14.png",
    plot = figure14,
    width = 10,
    height = 8
)

```


```{r figure15}
dat = dat = dat_na %>%
    filter(Q1.1 == 'Combination' | Q1.1 == 'Developers') %>%
    select(Q1.1, Q8.3_1, Q8.3_2, Q8.3_3, Q8.3_4, Q8.3_5, Q8.3_6)

datm = reshape2::melt(
    dat,
    id.vars = 'Q1.1',
    value.name = 'Choice',
    variable.name = 'Question'
)

datm$Choice = factor(
    datm$Choice,
    levels = c(
        'Never',
        'Sometimes',
        'About half the timet',
        'Most of the time',
        'Always'
    )
)
datm$Question = factor(
    datm$Question,
    labels = c(
        "Q8.3_1" = "(Co)author on research paper",
        "Q8.3_2" = "(Co)author on software paper",
        "Q8.3_3" = "Acknowledgment in paper",
        "Q8.3_4" = "Software cited in a paper",
        "Q8.3_5" = "Funded/hired to work on the software",
        "Q8.3_6" = "Other"
    )
)

datmm = datm %>%
    filter(!is.na(Choice))

figure15 <- ggplot(datmm, aes(x = Q1.1, fill = Choice)) +
    facet_wrap("Question", labeller = label_wrap_gen(width = 25)) +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(
        axis.text.x = element_text(angle = 40, hjust = 1, size = rel(1.2)),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(),
        legend.position = 'bottom'
    ) 

figure15

ggsave(
    file = "svg/figure_15.svg",
    plot = figure15,
    width = 10,
    height = 8
)
 ggsave(
    file = "png/figure_15.png",
    plot = figure15,
    width = 10,
    height = 8
)
 
```


```{r figure16}
dat_na$Q8.4 = ifelse(
    dat_na$Q8.4 == 'Dependent on the position (programmer vs. faculty)',
    'Depends',
    dat_na$Q8.4
)

dat_na$Q8.4 = factor(dat_na$Q8.4, levels = c('No', 'Depends', 'Yes'))

dat = dat_na %>%
    filter(!is.na(Q1.1) & !is.na(Q8.4)) %>%
    select(Q1.1, Q8.4)



figure16 <- ggplot(dat, aes(x = Q1.1, fill = Q8.4)) +
    geom_bar(position = "dodge", color = "black") +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
    theme(
        axis.text.x = element_text(angle = 40, hjust = 1, size = rel(1.2)),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom'
    ) +
    ggtitle("Does Institution Consider Software Contributions In Performance Reviews Or Promotion Cases")
figure16
ggsave(
    file = "svg/figure_16.svg",
    plot = figure16,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_16.png",
    plot = figure16,
    width = 10,
    height = 8
)


```


```{r figure17}

dat_na$Q8.5 = factor(
    dat_na$Q8.5,
    levels = c(
        'Not at all important',
        'Slightly important',
        'Moderately important',
        'Very important',
        'Extremely important'
    )
)

dat = dat_na %>%
    filter(!is.na(Q1.1) & !is.na(Q8.5)) %>%
    select(Q1.1, Q8.5)



figure17 <- ggplot(dat, aes(x = Q1.1, fill = Q8.5)) +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(
        axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom'
    ) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE)) +
    ggtitle("Importance Of Software Contributions During Performance Review Or Promotion")
figure17
ggsave(
    file = "svg/figure_17.svg",
    plot = figure17,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_17.png",
    plot = figure17,
    width = 10,
    height = 8
)


```


```{r figure18}
dat = dat_na %>%
    filter(!is.na(Q1.1)) %>%
    select(Q1.1, Q9.2_1, Q9.2_2, Q9.2_3, Q9.2_4)

datm = reshape2::melt(
    dat,
    id.vars = 'Q1.1',
    value.name = 'Choice',
    variable.name = 'Question'
)

datm$Choice = factor(datm$Choice,
                     levels = c('Terrible', 'Poor', 'Average', 'Good', 'Excellent'))
datm$Question = factor(
    datm$Question,
    labels = c(
        "Q9.2_1" = "Recruit participants from underrepresented groups",
        "Q9.2_2" = "Retain participants from underrepresented groups",
        "Q9.2_3" = "Include participants from underrepresented groups in governance and leadership positions",
        "Q9.2_4" = "Maintain a culture of inclusion"
    )
)

datmm = datm %>%
    filter(!is.na(Choice))

figure18 <- ggplot(datmm, aes(x = Q1.1, fill = Choice)) +
    facet_wrap("Question", labeller = label_wrap_gen(width = 40)) +
    geom_bar(position = "dodge", color = "black") +
    scale_fill_viridis(discrete = TRUE) +
    labs(x = '', y = 'Frequency') +
    theme(
        axis.text.x = element_text(angle = 40, hjust = 1, size = rel(1.2)),
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom'
    ) 


figure18
ggsave(
    file = "svg/figure_18.svg",
    plot = figure18,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_18.png",
    plot = figure18,
    width = 10,
    height = 8
)

```



```{r figure9}
dat = dat_na %>%
    filter(Q1.1 == "Combination" &
               !is.na(Q14.2) | Q1.1 == "Developers" & !is.na(Q14.2)) %>%
    select(Q1.1, Q14.2)

tmp3 = tmp2 %>%
    filter(Areas == "Funding / Institutional Support") %>%
    select(-Areas)

dat$Q14.2 = factor(
    dat$Q14.2,
    levels = c(
        "Insufficient and creates barrier to my work",
        "2",
        "3",
        "4",
        "Sufficient to do my work"
    )
)

figure9 <- ggplot(dat, aes(x = Q14.2, fill = Q1.1)) +
    geom_bar(color = "black") +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
    theme(
        axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        legend.position = 'bottom',
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank()
    ) +
    scale_x_discrete(
        drop = F,
        labels = c(
            "Insufficient and\n creates barrier\n to my work",
            "2",
            "3",
            "4",
            "Sufficient to do\n my work"
        )
    ) 
figure9
ggsave(
    file = "svg/figure_9.svg",
    plot = figure9,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_9.png",
    plot = figure9,
    width = 10,
    height = 8
)

```




```{r figure13}
dat = dat_na %>%
    filter(Q1.1 == "Combination" | Q1.1 == "Developers") %>%
    select(Q1.1, Q15.3_1, Q15.3_2, Q15.3_3, Q15.3_4, Q15.3_5, Q15.3_6)

datm = reshape2::melt(
    dat,
    id.vars = 'Q1.1',
    value.name = 'Choice',
    variable.name = 'Question'
)

datmm = datm %>%
    filter(!is.na(Choice))

datmm$Question = factor(
    datmm$Question,
    labels = c(
        "Q15.3_1" = "Title of the position",
        "Q15.3_2" = "Salary raise",
        "Q15.3_3" = "Responsibilities for a project or parts of a project",
        "Q15.3_4" = "Leading a team",
        "Q15.3_5" = "Available resources such as travel money",
        "Q15.3_6" = "Other"
    )
)

datmm$Choice = factor(
    datmm$Choice,
    levels = c(
        "Extremely important",
        "Very important",
        "Moderately important",
        "Slightly important",
        "Not at all important"
    )
)

figure13 <- ggplot(datmm, aes(x = Q1.1, fill = Choice)) +
    facet_wrap("Question", labeller = label_wrap_gen(width = 25)) +
    geom_bar(color = "black", position = position_dodge2(width = 0.9, preserve = "single")) +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
    theme(
        axis.text.x = element_text(angle = 30, hjust = 1, size = rel(1.2)),
        legend.position = 'bottom',
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank()
    ) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE)) 

figure13
ggsave(
    file = "svg/figure_13.svg",
    plot = figure13,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_13.png",
    plot = figure13,
    width = 10,
    height = 8
)

```




```{r figure19}
dat = dat_na %>%
    filter(!is.na(Q1.1) & !is.na(Q17.1)) %>%
    select(Q1.1, Q17.1)

tmp3 = tmp2 %>%
    filter(Areas == "Diversity / Inclusion") %>%
    select(-Areas)

dat$Q17.1 = factor(
    dat$Q17.1,
    levels = c(
        'Yes',
        'No, but we plan to develop one',
        'No, and we do not plan to develop one',
        'Other'
    )
)

figure19 <- ggplot(dat, aes(x = Q17.1, fill = Q1.1)) +
    geom_bar(color = "black", position = "dodge") +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
      theme(
        axis.text.x = element_text(
            angle = 30,
            hjust = 1,
            size = rel(1.3)
            ),
        axis.text.y = element_text(
            hjust = 1,
            size = rel(1.3)
        ),
        legend.position = 'bottom',
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank() 
    ) + scale_x_discrete(labels=c("Yes", "No, will develop", "No, will not develop", "Other"))
figure19
ggsave(
    file = "svg/figure_19.svg",
    plot = figure19,
    width = 10,
    height = 8
)
ggsave(
    file = "png/figure_19.png",
    plot = figure19,
    width = 10,
    height = 8
)

```



```{r figure20}
dat = dat_na %>%
    filter(Q1.1 == "Combination" &
               !is.na(Q17.3) | Q1.1 == "Developers" & !is.na(Q17.3)) %>%
    select(Q1.1, Q17.3)


dat$Q17.3 = factor(
    dat$Q17.3,
    levels = c(
        'Yes',
        'No, but we plan to develop one',
        'No, and we do not plan to develop one',
        'Other'
    )
)

figure20 <- ggplot(dat, aes(x = Q17.3, fill = Q1.1)) +
    geom_bar(color = "black", position = position_dodge2(width = 0.9, preserve = "single")) +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
      theme(
        axis.text.x = element_text(
            angle = 30,
            hjust = 1,
            size = rel(1.3)
            ),
        axis.text.y = element_text(
            hjust = 1,
            size = rel(1.3)
        ),
        legend.position = 'bottom',
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank() 
    )
figure20

ggsave(
    file = "svg/figure_20.svg",
    plot = figure20,
    width = 10,
    height = 8
)

ggsave(
    file = "png/figure_20.png",
    plot = figure20,
    width = 10,
    height = 8
)

```



```{r figure21}
dat <- dat_na %>%
    filter(!is.na(Q1.1) & !is.na(Q17.5)) %>%
    select(Q1.1, Q17.5)


dat$`Recruiting diverse participants` = ifelse(str_detect(dat$Q17.5, 'Recruiting diverse participants') ==
                                                   T,
                                               'Included',
                                               'Not')
dat$`Retaining diverse participants` = ifelse(str_detect(dat$Q17.5, 'Retaining diverse participants') ==
                                                  T,
                                              'Included',
                                              'Not')
dat$`Including diverse participants in governance and leadership positions` = ifelse(
    str_detect(
        dat$Q17.5,
        'Including diverse participants in governance and leadership positions'
    ) == T,
    'Included',
    'Not'
)
dat$`Developing a code of conduct` = ifelse(str_detect(dat$Q17.5, 'Developing a code of conduct') ==
                                                T,
                                            'Included',
                                            'Not')
dat$`Developing a diversity / inclusivity policy` = ifelse(
    str_detect(dat$Q17.5, 'Developing a diversity / inclusivity policy') == T,
    'Included',
    'Not'
)

datm = reshape2::melt(
    dat[, -2],
    id.vars = 'Q1.1',
    value.name = 'Included',
    variable.name = 'Practice'
)

datmm = datm %>%
    filter(Included == 'Included')

figure21 <- ggplot(datmm, aes(x = Practice, fill = Q1.1)) +
    geom_bar(color = "black", position = position_dodge2(width = 0.9, preserve = "single")) +
    labs(x = '', y = 'Frequency') +
    scale_fill_viridis(discrete = TRUE) +
    theme(
        axis.text.x = element_text(
            angle = 30,
            hjust = 1,
            size = rel(1.3)
            ),
        axis.text.y = element_text(
            hjust = 1,
            size = rel(1.3)
        ),
        legend.position = 'bottom',
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank() 
    ) +
    scale_x_discrete(
        labels = c(
            'Recruiting\n diverse participants',
            'Retaining\n diverse participants',
            'Including diverse participants\n in governance and leadership positions',
            'Developing a code\n of conduct',
            'Developing a diversity/\n inclusivity policy'
        )
    ) 

figure21
ggsave(
    file = "svg/figure_21.svg",
    plot = figure21,
    width = 10,
    height = 8
)

ggsave(
    file = "png/figure_21.png",
    plot = figure21,
    width = 10,
    height = 8
)

```